//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_01_ALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderList()
        {
            this.AnalyzerOperation = new HashSet<AnalyzerOperation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public Nullable<int> ID_ServiceStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalyzerOperation> AnalyzerOperation { get; set; }
        public virtual Order Order { get; set; }
        public virtual Services Services { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; }
    }
}
