//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_01_ALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenderingOfServisec
    {
        public int ID { get; set; }
        public Nullable<int> ID_Users { get; set; }
        public Nullable<int> ID_Services { get; set; }
        public Nullable<int> ID_Analyzer { get; set; }
        public Nullable<System.DateTime> Rendered { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
